site_name: 'xpcc microcontroller framework'
site_author: 'Roboterclub Aachen e.V.'
site_url: 'http://docs.xpcc.io'
repo_name: GitHub
repo_url: 'https://github.com/RoboterclubAachen/xpcc'
copyright: 'Copyright &copy 2016 Roboterclub Aachen e.V.'

extra_css: [extra.css]

theme: 'material'
extra:
  palette:
    primary: 'indigo'
    accent: 'cyan'
  logo: 'images/logo.svg'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  author:
    github: 'RoboterclubAachen'
    twitter: 'RCA_eV'


markdown_extensions:
  - codehilite(css_class=code)
  - toc:
      permalink: '#'
  - admonition
  - sane_lists
  - abbr
  - tables
  - attr_list
  - footnotes
  - def_list
  - latex_math
  - markdeep_diagram

pages:
  - Home: index.md
  - Why use xpcc?: why-use-xpcc.md
  - Installation: installation.md
  - Guide:
    - Getting started: guide/getting-started.md
#    - Testing: guide/testing.md
  - Reference:
    - API reference: reference/api.md
    - Build system: reference/build-system.md
