site_name: 'xpcc microcontroller framework'
site_author: 'Roboterclub Aachen e.V.'
site_url: 'http://docs.xpcc.io'
repo_name: GitHub
repo_url: 'https://github.com/RoboterclubAachen/xpcc'
copyright: 'Copyright &copy 2016 Roboterclub Aachen e.V.'

theme: 'material'
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
  logo: 'images/logo.svg'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  author:
    github: 'RoboterclubAachen'
    twitter: 'RCA_eV'


markdown_extensions:
  - codehilite(css_class=code)
  - toc:
      permalink: 'Â¶'
  - admonition
  - sane_lists
  - abbr
  - tables
  - attr_list
  - footnotes
  - def_list
  - latex_math

